services:
  app:
    image: node:18-alpine
    # command: sh -c "yarn install && yarn run dev"
    command: ["tail", "-f", "/dev/null"]
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    # environment:
    #   MYSQL_HOST: mysql-db
    #   MYSQL_USER: root
    #   MYSQL_PASSWORD: secret
    #   MYSQL_DB: todos
    networks:
      - todo-network

  mysql:
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    hostname: mysql-db
    networks:
      - todo-network

volumes:
  todo-mysql-data:

networks:
  todo-network:
    driver: bridge
